package com.chalkak.backend.exception;

public enum ErrorCode {
    BUSINESS_ERROR,
    SIGNATURE_REGISTRATION_REQUIRED,
    SIGNATURE_REUPLOAD_REQUIRED,
    SIGNATURE_PROCESSING_PENDING,
    POST_MODERATION_STATE_INVALID,
    POST_DELETION_STATE_INVALID,
    UNAUTHORIZED,
    FORBIDDEN
}
