package com.chalkak.backend.exception;

public enum ErrorCode {
    BUSINESS_ERROR,
    SIGNATURE_REGISTRATION_REQUIRED,
    SIGNATURE_REUPLOAD_REQUIRED,
    SIGNATURE_PROCESSING_PENDING,
    RESOURCE_STATE_CHANGED,
    UNAUTHORIZED,
    FORBIDDEN
}
