ALTER TABLE users ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE topics ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE photos ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE posts ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE admins ALTER COLUMN id SET DEFAULT uuidv7();
