"use client";
import { useState, type FormEvent } from "react";
import type { AdminTopicMutation } from "../api/topic-api";
import { instantToKstInput, kstInputToInstant } from "../model/topic-display";
import styles from "@/shared/ui/management.module.css";

interface Values{title:string;topicDate:string;startsAt:string;endsAt:string}
export function TopicForm({initial,onSubmit,pending,submitLabel="저장",onCancel}:{initial?:AdminTopicMutation;onSubmit:(value:AdminTopicMutation)=>Promise<void>;pending:boolean;submitLabel?:string;onCancel?:()=>void}){
 const [values,setValues]=useState<Values>({title:initial?.title??"",topicDate:initial?.topicDate??"",startsAt:initial?instantToKstInput(initial.startsAt):"",endsAt:initial?instantToKstInput(initial.endsAt):""});
 const [errors,setErrors]=useState<Partial<Record<keyof Values,string>>>({});
 const change=(key:keyof Values,value:string)=>setValues(current=>({...current,[key]:value}));
 const submit=async(event:FormEvent)=>{event.preventDefault();const next:typeof errors={};if(!values.title.trim())next.title="제목을 입력해 주세요.";if(!values.topicDate)next.topicDate="주제 날짜를 선택해 주세요.";if(!values.startsAt)next.startsAt="시작 시각을 입력해 주세요.";if(!values.endsAt)next.endsAt="종료 시각을 입력해 주세요.";if(values.startsAt&&values.endsAt&&values.endsAt<=values.startsAt)next.endsAt="종료 시각은 시작 시각보다 뒤여야 합니다.";if(values.startsAt&&values.topicDate&&values.startsAt.slice(0,10)!==values.topicDate)next.topicDate="주제 날짜는 참여 시작일과 같아야 합니다.";setErrors(next);if(Object.keys(next).length)return;await onSubmit({title:values.title.trim(),topicDate:values.topicDate,startsAt:kstInputToInstant(values.startsAt),endsAt:kstInputToInstant(values.endsAt)});};
 return <form className={styles.form} onSubmit={submit}><div className={styles.formGrid}><label><span>주제 제목</span><input aria-label="주제 제목" maxLength={255} onChange={e=>change("title",e.target.value)} value={values.title}/>{errors.title?<small className={styles.formError}>{errors.title}</small>:null}</label><label><span>주제 날짜</span><input aria-label="주제 날짜" onChange={e=>change("topicDate",e.target.value)} type="date" value={values.topicDate}/>{errors.topicDate?<small className={styles.formError}>{errors.topicDate}</small>:null}</label><label><span>참여 시작 (한국 시간)</span><input aria-label="참여 시작" onChange={e=>change("startsAt",e.target.value)} type="datetime-local" value={values.startsAt}/>{errors.startsAt?<small className={styles.formError}>{errors.startsAt}</small>:null}</label><label><span>참여 종료 (한국 시간)</span><input aria-label="참여 종료" onChange={e=>change("endsAt",e.target.value)} type="datetime-local" value={values.endsAt}/>{errors.endsAt?<small className={styles.formError}>{errors.endsAt}</small>:null}</label></div><div className={styles.formActions}>{onCancel?<button className={styles.secondaryButton} disabled={pending} onClick={onCancel} type="button">취소</button>:null}<button className={styles.primaryButton} disabled={pending} type="submit">{pending?"저장 중…":submitLabel}</button></div></form>;
}
