spring:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:chalkak}
    username: ${POSTGRES_USER:chalkak}
    password: ${POSTGRES_PASSWORD:local-password}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug